const allStaticCards = [
  { id: "1", word: "bus", color: "red", is_open: 0, game: "khsfhk" },
  { id: "2", word: "code", color: "red", is_open: 0, game: "khsfhk" },
  { id: "3", word: "success", color: "red", is_open: 0, game: "khsfhk" },
  { id: "4", word: "water", color: "red", is_open: 0, game: "khsfhk" },
  { id: "5", word: "book", color: "red", is_open: 0, game: "khsfhk" },
  { id: "6", word: "cup", color: "red", is_open: 0, game: "khsfhk" },
  { id: "7", word: "light", color: "red", is_open: 0, game: "khsfhk" },
  { id: "8", word: "phone", color: "red", is_open: 0, game: "khsfhk" },
  { id: "9", word: "wall", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "10", word: "sticker", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "11", word: "cold", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "12", word: "hot", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "13", word: "paper", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "14", word: "pen", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "15", word: "color", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "16", word: "bottle", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "17", word: "talk", color: "blue", is_open: 0, game: "khsfhk" },
  { id: "18", word: "hair", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "19", word: "computer", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "20", word: "guitar", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "21", word: "singing", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "22", word: "icecream", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "23", word: "painting", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "24", word: "notebook", color: "grey", is_open: 0, game: "khsfhk" },
  { id: "25", word: "lipstick", color: "black", is_open: 0, game: "khsfhk" },
];

export default allStaticCards;
